import { NextResponse, type NextProxy } from "next/server"

import { auth } from "@/auth"

/*
 * Route protection. Everything except the auth endpoints, the login page, the
 * health check and static assets requires a signed-in @elvtr.com session — the
 * run API included, so a deck can never be generated by an anonymous caller.
 */

/*
 * Local preview skips the session gate. The gate that makes that safe is the
 * BUILD, not the hostname: `next dev` runs with NODE_ENV=development and
 * `next start` with production, and NODE_ENV is not something a request can
 * influence.
 *
 * It deliberately does NOT test request.nextUrl.hostname. That reads the
 * request's own Host, so it is caller-controlled in principle — and in Next 16
 * it does not even resolve to the requested host, so a hostname check here
 * silently passed every request instead of refusing non-local ones. A switch
 * that claims "localhost only" has to be enforced by something the caller
 * cannot set.
 */
const localPreviewEnabled =
  process.env.MEETBALL_LOCAL_PREVIEW === "1" && process.env.NODE_ENV !== "production"

// Staging review before OAuth credentials exist: skips the session gate on
// every host, and says so. Remove MEETBALL_PUBLIC_PREVIEW from the environment
// once AUTH_GOOGLE_ID / AUTH_GOOGLE_SECRET are set.
const openProxy: NextProxy = () => NextResponse.next()

export const proxy =
  process.env.MEETBALL_PUBLIC_PREVIEW === "1" || localPreviewEnabled ? openProxy : auth

export const config = {
  // hero/fonts stay public: the login page renders them before there is a
  // session, and the image optimizer fetches sources without the visitor's cookie.
  matcher: [
    "/((?!api/auth|api/health|login|hero|fonts|_next/static|_next/image|favicon.ico|icon.png|apple-icon.png|robots.txt|sitemap.xml).*)",
  ],
}
