import { NextResponse, type NextProxy } from "next/server"

import { auth } from "@/auth"

/*
 * Route protection, mirroring photo-booth/src/proxy.ts. Everything except the
 * auth endpoints, the login page, the health check and static assets requires
 * a signed-in @elvtr.com session — the run API included, so a deck can never
 * be generated by an anonymous caller.
 */

const localPreviewProxy: NextProxy = (request) => {
  const localHost =
    request.nextUrl.hostname === "127.0.0.1" || request.nextUrl.hostname === "localhost"

  if (localHost) return NextResponse.next()

  return new Response("Local preview is only available on localhost.", { status: 403 })
}

// Staging review before OAuth credentials exist: skips Google auth on every
// host. Remove MEETBALL_PUBLIC_PREVIEW from the environment once
// AUTH_GOOGLE_ID / AUTH_GOOGLE_SECRET are set.
const publicPreviewProxy: NextProxy = () => NextResponse.next()

export const proxy =
  process.env.MEETBALL_PUBLIC_PREVIEW === "1"
    ? publicPreviewProxy
    : process.env.MEETBALL_LOCAL_PREVIEW === "1"
      ? localPreviewProxy
      : auth

export const config = {
  // hero/fonts stay public: the login page renders them before there is a
  // session, and the image optimizer fetches sources without the visitor's cookie.
  matcher: [
    "/((?!api/auth|api/health|login|hero|fonts|_next/static|_next/image|favicon.ico|icon.png|apple-icon.png|robots.txt|sitemap.xml).*)",
  ],
}
